Repository TheGoatGod/Community-Mod-Compilation, pull requests merged in 2021-02, with the labels that each got.

#255 [Experimental] working mods fix
  data/Unleash_The_Mods/Working_mods/Abrahms_Recipes/items/tool/cooking.json
  data/Unleash_The_Mods/Working_mods/Arendeths_Mutant_Cyborg_Profession/scenarios.json
  data/Unleash_The_Mods/Working_mods/Bionic_Space_Expander/bionics.json
Labels: Experimental F, bug

#266 [Experimental] time update rebalance mods
  data/Rebalance_mods/mods/Anesthetic_Crafting/recipe.json
  data/Rebalance_mods/mods/M_Blazemod_Extension/recipe_blob_A.json
  data/Rebalance_mods/mods/Mutation_Changes_Mod_fix/recipe_meds_and_chemicals.json
  data/Rebalance_mods/mods/Reapermod/recipes.json
  data/Rebalance_mods/mods/Road_Warrior_Mod/mm_recipe_armor.json
  data/Rebalance_mods/mods/SD_Winterclothes/winterrecipes.json
  data/Rebalance_mods/mods/ShardsOtherStuff_UNINSTALLED/Anesthesia_Crafting/recipe.json
  data/Rebalance_mods/mods/ShardsOtherStuff_UNINSTALLED/Soapywater_CDDA/soapywater.json
  data/Rebalance_mods/mods/Winning_DDA/Arcana/construction.json
  data/Rebalance_mods/mods/Winning_DDA/Arcana/recipe.json
  data/Rebalance_mods/mods/Winning_DDA/Arcana/recipe_other_WIN.json
  data/Rebalance_mods/mods/Winning_DDA/Blazemod/diamond/blaze_vt_recipes.json
  data/Rebalance_mods/mods/ZSFixed_CDDAXP/CDDAXP_Recipes.json
  data/Rebalance_mods/mods/Zets_CDDA_Mod/adv_gear_recipe_equipment.json
Labels: Experimental F

#272 [Documentation] Update Updating_Legacy_JSON.md
  Documents/Updating_Legacy_JSON.md
Labels: documentation

#267 [Experimental] time update mainline mods
  data/Mainline_mods/Mods/Aftershock/recipes/armor_recipes.json
  data/Mainline_mods/Mods/Aftershock/recipes/comestible_recipes.json
  data/Mainline_mods/Mods/Aftershock/recipes/construction.json
  data/Mainline_mods/Mods/Aftershock/recipes/frankenstein_recipes.json
  data/Mainline_mods/Mods/Aftershock/recipes/mutagens.json
  data/Mainline_mods/Mods/Aftershock/recipes/recipe_overrides.json
  data/Mainline_mods/Mods/Aftershock/recipes/recipes.json
  data/Mainline_mods/Mods/Aftershock/recipes/robot_recipes.json
  data/Mainline_mods/Mods/CRT_EXPANSION/items/crt_recipes.json
  data/Mainline_mods/Mods/CrazyCataclysm/crazy_aperturepotato.json
  data/Mainline_mods/Mods/CrazyCataclysm/crazy_comestibles.json
  data/Mainline_mods/Mods/DinoMod/recipe_medsandchemicals.json
Labels: Experimental F

#268 [Experimental] time update legacy mods
  data/Legacy_mods/mods/Craft_Gunpowder/cgp_recipes.json
  data/Legacy_mods/mods/FictonalWeapons/fic_recipes.json
  data/Legacy_mods/mods/Medieval_Stuff/recipe_ammo.json
  data/Legacy_mods/mods/Medieval_Stuff/recipe_shields.json
  data/Legacy_mods/mods/Medieval_Stuff/recipe_weapon.json
  data/Legacy_mods/mods/More_Survival_Tools/recipes.json
  data/Legacy_mods/mods/NW_Pack/nw_recipes.json
  data/Legacy_mods/mods/Salvaged_Robots/recipe.json
  data/Legacy_mods/mods/Tanks/recipes.json
  data/Legacy_mods/mods/bio_mod/construction/furniture.json
  data/Legacy_mods/mods/bio_mod/recipies/bionics.json
  data/Legacy_mods/mods/bio_mod/recipies/food.json
  data/Legacy_mods/mods/bio_mod/recipies/furniture.json
  data/Legacy_mods/mods/bio_mod/recipies/medicine.json
  data/Legacy_mods/mods/blazemod/blob_construction.json
  data/Legacy_mods/mods/fast_healing/recipes.json
  data/Legacy_mods/mods/makeshift/recipe.json
  data/Legacy_mods/mods/necromancy/necronimicron.json
Labels: Experimental F

#269 [Experimental] time update broken mods
  data/broken_mods/Alchemic_bomb/alc_construction.json
  data/broken_mods/Alchemic_bomb/alc_recipe.json
  data/broken_mods/EW_Pack/ew_recipes.json
  data/broken_mods/Pizza_Delivery/recipe_vehicle.json
  data/broken_mods/Standalone_Salvaged_Robots/corpses_SR.json
  data/broken_mods/Standalone_Salvaged_Robots/recipe.json
  data/broken_mods/Standalone_Salvaged_Robots/recipe_SR.json
Labels: Experimental F

#258 [Experimental] fix for vehicle json
  data/Legacy_mods/mods/HeavyMining/vehicles.json
  data/Legacy_mods/mods/Salvaged_Robots/robot_additions/vehicles.json
  data/Legacy_mods/mods/Tanks/vehicles.json
  data/Mainline_mods/Mods/Aftershock/vehicles/vehicle_overrides.json
  data/Mainline_mods/Mods/Aftershock/vehicles/vehicles.json
  data/Mainline_mods/Mods/CrazyCataclysm/crazy_vehicles.json
  data/Mainline_mods/Mods/Magiclysm/vehicles/summoned_vehicles.json
  data/Mainline_mods/Mods/Magiclysm/vehicles/vans_busses.json
  data/Maintained_mods/mods/Nocts_cata_mod/Vehicles/c_vehicles.json
  data/Maintained_mods/mods/Tankmod_Revived/vehicles.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/vehicles/modified.json
  data/Maintained_mods/mods/expansion_tefnut/vehicles/modified.json
  data/Rebalance_mods/mods/Road_Warrior_Mod/mm_vehicles.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_vehicles.json
  data/Unleash_The_Mods/mods/Tekitoumap/vehicles/carts.json
  data/Unleash_The_Mods/mods/Tekitoumap/vehicles/vehicles.json
  data/broken_mods/Pizza_Delivery/vehicles.json
  data/broken_mods/Standalone_Salvaged_Robots/robot_additions/vehicles.json
  data/unleash_The_Mods/mods/Advanced_Technologies/at_vehicles.json
  data/unleash_The_Mods/mods/Bright_Nights/vehicles/cars.json
  data/unleash_The_Mods/mods/Custom_Bandit_King_Start/vehicles.json
  data/unleash_The_Mods/mods/Dorf_Life/vehicles.json
  data/unleash_The_Mods/mods/Draco_Dog_Mod/vehicles/dg_vehicles.json
  data/unleash_The_Mods/mods/Engineering_Essentials/vehicles.json
  data/unleash_The_Mods/mods/Fallout/Gunsmiths_Guru/items/Alien_Stuff/zetan_craft.json
  data/unleash_The_Mods/mods/Fallout/Items/Alien_Stuff/zetan_craft.json
  data/unleash_The_Mods/mods/Fallout/vehicle_gunrunner/gunrunners.json
  data/unleash_The_Mods/mods/Jury_Rigged_Robots/jrr_vehicle.json
  data/unleash_The_Mods/mods/Mo_Vehicles/veh.json
  data/unleash_The_Mods/mods/More_Makeshift_Stuff/mod_vehicles.json
  data/unleash_The_Mods/mods/Ninja_mod/ninja_vehicle.json
  data/unleash_The_Mods/mods/Oa_additional_buildings/json/cs_open_sewer_small.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/vehicle/pk_vehicle_bfg.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/vehicle/pk_vehicle_doubleplow.json
  data/unleash_The_Mods/mods/Ships/oa_shared_vehicles.json
  data/unleash_The_Mods/mods/Trailerpark_mod/vehicle_bandit.json
  data/unleash_The_Mods/mods/Trailerpark_mod/vehicle_trailers.json
  data/unleash_The_Mods/mods/Trailerpark_mod/vehicle_trailers2.json
  data/unleash_The_Mods/mods/Variety_pack/vehicles/large_work_light.json
  data/unleash_The_Mods/mods/Variety_pack/vehicles/pickup_eb.json
  data/unleash_The_Mods/mods/Variety_pack/vehicles/pickup_ec.json
  data/unleash_The_Mods/mods/Variety_pack/vehicles/pickup_elec_basic.json
  data/unleash_The_Mods/mods/Variety_pack/vehicles/pickup_elec_up.json
  data/unleash_The_Mods/mods/Variety_pack/vehicles/small_work_light.json
  data/unleash_The_Mods/mods/miso_Touhou/vehicles_touhou/vehicles.json
Labels: Experimental F, invalid

#273 [Experimental] volume update
  data/Maintained_mods/mods/BL9_100%_monster_resilience_version/Items/ammo.json
  data/Maintained_mods/mods/BL9_140%_monster_resilience_version/Items/ammo.json
  data/Maintained_mods/mods/BL9_175%_monster_resilience_version/Items/ammo.json
  data/Maintained_mods/mods/Nocts_cata_mod/Surv_help/c_bionics.json
  data/Unleash_The_Mods/Working_mods/More_Survivors_Stories/bandit_route/items.json
  data/unleash_The_Mods/mods/No_Hope_Night_Pryanik/Items/gunmods.json
  data/unleash_The_Mods/mods/Project_APEX/items/suit/modules.json
  data/unleash_The_Mods/mods/Reproduction_mod/Items/item.json
  data/unleash_The_Mods/mods/Wandering_Masters/items/items_quest.json
Labels: Experimental F

#275 [Tools]
  .flake8
  Tools/run_vehicle_reformatter.py
Labels: Experimental F

#279 [Experimental] update mainline mods
  data/Mainline_mods/Mods/Aftershock/harvest.json
  data/Mainline_mods/Mods/Aftershock/itemgroups/gun_groups.json
  data/Mainline_mods/Mods/Aftershock/items/ammo/plasma.json
  data/Mainline_mods/Mods/Aftershock/items/armor.json
  data/Mainline_mods/Mods/Aftershock/items/books.json
  data/Mainline_mods/Mods/Aftershock/items/comestibles/comestibles.json
  data/Mainline_mods/Mods/Aftershock/items/crafting_scrap/energy_storage_scrap.json
  data/Mainline_mods/Mods/Aftershock/items/crafting_scrap/material_scrap.json
  data/Mainline_mods/Mods/Aftershock/items/gun/migrations.json
  data/Mainline_mods/Mods/Aftershock/items/gun/plasma.json
  data/Mainline_mods/Mods/Aftershock/items/gunmods/laser_gunmods.json
  data/Mainline_mods/Mods/Aftershock/items/gunmods/sights.json
  data/Mainline_mods/Mods/Aftershock/items/items.json
  data/Mainline_mods/Mods/Aftershock/items/magazine/alien.json
  data/Mainline_mods/Mods/Aftershock/items/magazine/energy_cell.json
  data/Mainline_mods/Mods/Aftershock/items/magazine/plasma.json
  data/Mainline_mods/Mods/Aftershock/maps/mapgen/whately_lmoe.json
  data/Mainline_mods/Mods/Aftershock/mobs/mutants.json
  data/Mainline_mods/Mods/Aftershock/mobs/robots.json
  data/Mainline_mods/Mods/Aftershock/mobs/zombies.json
  data/Mainline_mods/Mods/Aftershock/npcs/classes.json
  data/Mainline_mods/Mods/Aftershock/npcs/sadie.json
  data/Mainline_mods/Mods/Aftershock/player/professions.json
  data/Mainline_mods/Mods/Aftershock/recipes/recipes_categories.json
  data/Mainline_mods/Mods/Aftershock/vehicles/vehicle_parts.json
  data/Mainline_mods/Mods/DinoMod/NPC/NC_BO_BARONYX.json
  data/Mainline_mods/Mods/DinoMod/NPC/NC_Red.json
  data/Mainline_mods/Mods/Magiclysm/Spells/attunements/Boreal_Mage.json
  data/Mainline_mods/Mods/Magiclysm/Spells/attunements/Cleansing_Flame.json
  data/Mainline_mods/Mods/Magiclysm/Spells/attunements/Glacier_Mage.json
  data/Mainline_mods/Mods/Magiclysm/Spells/magus.json
  data/Mainline_mods/Mods/Magiclysm/Spells/stormshaper.json
  data/Mainline_mods/Mods/Magiclysm/Spells/technomancer.json
  data/Mainline_mods/Mods/Magiclysm/effects/effects.json
  data/Mainline_mods/Mods/Magiclysm/emitter.json
  data/Mainline_mods/Mods/Magiclysm/field.json
  data/Mainline_mods/Mods/Magiclysm/harvest.json
  data/Mainline_mods/Mods/Magiclysm/itemgroups/itemgroups.json
  data/Mainline_mods/Mods/Magiclysm/itemgroups/spellbooks.json
  data/Mainline_mods/Mods/Magiclysm/items/spell_scrolls.json
  data/Mainline_mods/Mods/Magiclysm/items/spellbooks.json
  data/Mainline_mods/Mods/Magiclysm/monster_factions.json
  data/Mainline_mods/Mods/Magiclysm/monstergroups.json
  data/Mainline_mods/Mods/Magiclysm/monsters/golems.json
  data/Mainline_mods/Mods/Magiclysm/monsters/holiday_magiclysm.json
  data/Mainline_mods/Mods/Magiclysm/npc/npc.json
  data/Mainline_mods/Mods/Magiclysm/professions.json
  data/Mainline_mods/Mods/Magiclysm/requirements/spell_components.json
  data/Mainline_mods/Mods/Magiclysm/species.json
  data/Mainline_mods/Mods/Magiclysm/traits/attunements.json
  data/Mainline_mods/Mods/Magiclysm/vehicles/summoned_vehicles.json
  data/Mainline_mods/Mods/Magiclysm/worldgen/magic_shop.json
  data/Maintained_mods/mods/Arcana/npcs/npcs.json
  data/Maintained_mods/mods/Nocts_cata_mod/Npc/c_npc.json
  data/Maintained_mods/mods/Nocts_cata_mod/removed.txt
  data/Unleash_The_Mods/Working_mods/Bootleg_Walkers/walker_recipes.json
Labels: Experimental F, added content

#277 [Experimental] rebalance mods fixes
  data/Rebalance_mods/mods/Battery_Migration/items/batt_mag.json
  data/Rebalance_mods/mods/Battery_Migration/modinfo.json
  data/Rebalance_mods/mods/Ex_Scen/ex_classes.json
  data/Rebalance_mods/mods/Ex_Scen/ex_scenarios.json
  data/Rebalance_mods/mods/Ex_Scen/ex_start_locations.json
  data/Rebalance_mods/mods/MkMaxxi_Gunslinger_Mod/Professions.json
  data/Rebalance_mods/mods/Mo_Creation/professions.json
  data/Rebalance_mods/mods/Mutation_Changes_Mod_fix/books.json
  data/Rebalance_mods/mods/Mutation_Changes_Mod_fix/mutagen.json
  data/Rebalance_mods/mods/Mutation_Changes_Mod_fix/mutations.json
  data/Rebalance_mods/mods/Mutation_Changes_Mod_fix/professions.json
  data/Rebalance_mods/mods/Mutation_Changes_Snofielf_Patch/mutation_category.json
  data/Rebalance_mods/mods/Mutation_Changes_Snofielf_Patch/mutations.json
  data/Rebalance_mods/mods/Mutation_Changes_Snofielf_Patch/professions.json
  data/Rebalance_mods/mods/Odds_N_Ends_mod_prototype/oe_ammo_50bmg.json
  data/Rebalance_mods/mods/Odds_N_Ends_mod_prototype/oe_armor.json
  data/Rebalance_mods/mods/Odds_N_Ends_mod_prototype/oe_tools.json
  data/Rebalance_mods/mods/Portable_Autodoc/game_balance.json
  data/Rebalance_mods/mods/Portable_Autodoc/modinfo.json
  data/Rebalance_mods/mods/Reapermod/tools.json
  data/Rebalance_mods/mods/Road_Warrior_Mod/factions.json
  data/Rebalance_mods/mods/Road_Warrior_Mod/gas_station.json
  data/Rebalance_mods/mods/Road_Warrior_Mod/mm_armor.json
  data/Rebalance_mods/mods/Road_Warrior_Mod/mm_regional_map_settings.json
  data/Rebalance_mods/mods/Road_Warrior_Mod/npc.json
  data/Rebalance_mods/mods/Road_Warrior_Mod/overmap_terrain.json
  data/Rebalance_mods/mods/Road_Warrior_Mod/warboy_camp.json
  data/Rebalance_mods/mods/Safe_Portable_Autodoc/medical_furniture.json
  data/Rebalance_mods/mods/Safe_Portable_Autodoc/modinfo.json
  data/Rebalance_mods/mods/Safe_autodoc/furniture-medical.json
  data/Rebalance_mods/mods/Safe_autodoc/furniture_medical.json
  data/Rebalance_mods/mods/Safe_autodoc/modinfo.json
  data/Rebalance_mods/mods/ShardsOtherStuff_UNINSTALLED/modinfo.json
  data/Rebalance_mods/mods/Wastelands_Mod-master/ammo.json
  data/Rebalance_mods/mods/Wastelands_Mod-master/armor.json
  data/Rebalance_mods/mods/Wastelands_Mod-master/mapgen/bandit_camp.json
  data/Rebalance_mods/mods/Wastelands_Mod-master/npcs/factions.json
  data/Rebalance_mods/mods/Wastelands_Mod-master/npcs/npc.json
  data/Rebalance_mods/mods/Wastelands_Mod-master/regional_map_settings.json
  data/Rebalance_mods/mods/ZSFixed_CDDAXP/CDDAXP_Armor.json
  data/Rebalance_mods/mods/ZSFixed_CDDAXP/CDDAXP_Ranged.json
  data/Rebalance_mods/mods/ZSFixed_CDDAXP/CDDAXP_Tools.json
  data/Rebalance_mods/mods/Zets_CDDA_Mod/adv_gear_equipment.json
  data/Rebalance_mods/mods/Zets_CDDA_Mod/cata++_c_armor.json
  data/Rebalance_mods/mods/more_classes_scenarios/cs_classes.json
  data/Rebalance_mods/mods/more_classes_scenarios/cs_professions.json
  data/Rebalance_mods/mods/more_classes_scenarios/cs_scenarios.json
Labels: Experimental F, code removal, enhancement, invalid, lint update

#260 [Experimental] Broken mod bug fixes
  data/broken_mods/Car_color_variation/vehicles.json
  data/broken_mods/OP_Pack/weapons.json
  data/broken_mods/Standalone_Salvaged_Robots/items_SR.json
  data/broken_mods/Standalone_Salvaged_Robots/monster.json
  data/broken_mods/Standalone_Salvaged_Robots/monsters_SR.json
  data/broken_mods/Standalone_Salvaged_Robots/monsters_override.json
  data/broken_mods/dmbbx_secronom/Modification_Files/Monsters/+Essentials/secro_magic.json
Labels: Experimental F, Legacy update, bug, code removal, invalid, lint update

#281 [Experimental]-[Tools] Update scripts and minor content changes.
  .flake8
  .gitignore
  Documents/Updating_Legacy_JSON.md
  Tools/barrellength_volume.py
  Tools/base_script.py
  Tools/covers_update.py
  Tools/material_ammo_update.py
  Tools/name.py
  Tools/name_strings_to_objects.py
  Tools/recipe_extractor_and_editor.py
  Tools/time_to_string.py
  Tools/vehicle_code.py
  Tools/vehicle_reformatter.py
  Tools/weight_update.py
  data/Unleash_The_Mods/Working_mods/More_Survivors_Stories/bandit_route/hells_raiders/forest_snakes/NPC_bandit_fs_recruiter.json
  data/Unleash_The_Mods/Working_mods/More_Survivors_Stories/bandit_route/hells_raiders/forest_snakes/NPC_bandit_fs_trapper.json
  data/Unleash_The_Mods/mods/Fallout/Gunsmiths_Guru/items/generic/clutter.json
  data/Unleash_The_Mods/mods/Fallout/Items/generic/clutter.json
  data/broken_mods/Alchemic_bomb/alc_item.json
  data/broken_mods/Car_color_variation/modinfo.json
  data/unleash_The_Mods/mods/Battle_Maid_Redux/melee.json
  data/unleash_The_Mods/mods/CBM_Arms/cbma_gun.json
  data/unleash_The_Mods/mods/Merchant/merchantitem.json
  data/unleash_The_Mods/mods/Vermilion_Mod/ver_weapons.json
Labels: Experimental F, Translation, documentation, enhancement, invalid

#286 [Experimental] legacy mod bug fixes
  data/Legacy_mods/mods/Tanks/treads.json
  data/Legacy_mods/mods/blazemod/vehicleparts/blaze_combustion.json
  data/Legacy_mods/mods/blazemod/vehicleparts/blaze_custom_turret.json
  data/Legacy_mods/mods/blazemod/vehicleparts/blaze_treads.json
  data/Legacy_mods/mods/blazemod/vehicleparts/blaze_weapons_parts.json
  data/broken_mods/OP_Pack/vehiclepart.json
Labels: Experimental F, bug

#285 [Experimental] unleash the mods bug fixes
  data/Maintained_mods/mods/More_Survivors_Stories/22ch/NPC_lead_scientist_22ch.json
  data/Maintained_mods/mods/More_Survivors_Stories/22ch/NPC_scientist_22ch.json
  data/Maintained_mods/mods/More_Survivors_Stories/Hartley_Family/Jerry_Squad/NPC_jerry_bumpkin.json
  data/Maintained_mods/mods/More_Survivors_Stories/Hartley_Family/NPC_Barrett_Hartley.json
  data/Maintained_mods/mods/More_Survivors_Stories/Hartley_Family/NPC_Rosalyn_Hartley.json
  data/Maintained_mods/mods/More_Survivors_Stories/bandit_route/hells_raiders/forest_snakes/NPC_bandit_fs_leader.json
  data/Maintained_mods/mods/More_Survivors_Stories/bandit_route/hells_raiders/forest_snakes/NPC_bandit_fs_recruiter.json
  data/Maintained_mods/mods/More_Survivors_Stories/bandit_route/hells_raiders/forest_snakes/NPC_bandit_fs_trapper.json
  data/Maintained_mods/mods/More_Survivors_Stories/bandit_route/hells_raiders/forest_snakes/NPC_unlucky_scavenger.json
  data/Maintained_mods/mods/More_Survivors_Stories/bandit_route/hells_raiders/red_suns/NPC_bandit_rs_bomber.json
  data/Maintained_mods/mods/More_Survivors_Stories/bandit_route/refugee_center/surface_staff/NPC_free_merchant_guard3.json_game
  data/Maintained_mods/mods/More_Survivors_Stories/bandit_route/refugee_center/surface_visitors/NPC_old_guard_representative.json_game
  data/Maintained_mods/mods/More_Survivors_Stories/mad_scientist/NPC_mad_scientist.json
  data/Maintained_mods/mods/More_Survivors_Stories/meteorologist/NPC_meteorologist.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_vehicle_parts.json
  data/Unleash_The_Mods/Working_mods/More_Survivors_Stories/bandit_route/hells_raiders/red_suns/NPC_bandit_rs_merchant.json
  data/Unleash_The_Mods/Working_mods/simple_additions/furniture_and_terrain/terrain-walls.json
  data/Unleash_The_Mods/Working_mods/simple_additions/items/armor/arms_armor.json
  data/Unleash_The_Mods/Working_mods/simple_additions/items/armor/helmets.json
  data/Unleash_The_Mods/Working_mods/simple_additions/items/armor/legs_armor.json
  data/Unleash_The_Mods/Working_mods/simple_additions/items/armor/torso_armor.json
  data/Unleash_The_Mods/Working_mods/simple_additions/items/chemicals_and_resources.json
  data/Unleash_The_Mods/Working_mods/simple_additions/items/comestibles/drink_other.json
  data/Unleash_The_Mods/Working_mods/simple_additions/items/comestibles/med.json
  data/Unleash_The_Mods/Working_mods/simple_additions/items/gun/blunderbuss.json
  data/Unleash_The_Mods/Working_mods/simple_additions/modinfo.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/armor/arms.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/armor/head.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/armor/legs.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/armor/legs_armor.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/armor/torso.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/chemicals.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/food/dry.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/other/medical.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/recipe_ammo.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/recipe_food.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/recipe_others.json
  data/Unleash_The_Mods/Working_mods/simple_additions/recipes/weapon/ranged.json
  data/unleash_The_Mods/mods/Advanced_Technologies/at_vehicle_parts.json
  data/unleash_The_Mods/mods/Fallout/Gunsmiths_Guru/items/Alien_Stuff/ufo_parts.json
  data/unleash_The_Mods/mods/Fallout/Gunsmiths_Guru/vehicle_parts/parts.json
  data/unleash_The_Mods/mods/Fallout/Items/Alien_Stuff/ufo_parts.json
  data/unleash_The_Mods/mods/Fallout/vehicle_parts.json
  data/unleash_The_Mods/mods/Generator_mod/vehicle_parts.json
  data/unleash_The_Mods/mods/More_Survivor_Stuff/vehicle_parts/vehicle_parts.json
Labels: Experimental F, bug

#293 workflows
  .github/workflows/Check_Markdown_links.yml
  .github/workflows/First_interaction.yml
  .github/workflows/tagged_release.yml
  CHANGELOG.md
  Workshop/Wilderness_Overhaul/README.md
  content.json
  data/Rebalance_mods/mods/Zets_Hair_Extensions/README.md
  data/Unleash_The_Mods/Working_mods/Modern_Weapons_Pack_Expanded/README.md
  data/unleash_The_Mods/mods/Food_Preservation_by_Irradiation/README.md
  data/unleash_The_Mods/mods/Homestead_Instruments_Inc/Doc/3D_PRINTED_ITEM.md
  data/unleash_The_Mods/mods/Homestead_Instruments_Inc/Doc/README.md
  data/unleash_The_Mods/mods/Private_Defense/README.md
  data/unleash_The_Mods/mods/Project_APEX/README.md
  index.md
  model.json
Labels: Experimental F

#295 [workflow] appease the typo workflow
  .typo-ci.yml
Labels: workflow

#298 [Github] Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#299 [Github] move pull request template
  PULL_REQUEST_TEMPLATE.md
Labels: GitHub

#292 [Experimental] rebalance mods updates
  data/Rebalance_mods/mods/M_Blazemod_Extension/blaze_blob_parts.json
  data/Rebalance_mods/mods/Winning_DDA/Arcana/construction.json
  data/Rebalance_mods/mods/Winning_DDA/Arcana/construction_groups.json
  data/Rebalance_mods/mods/Winning_DDA/Arcana/overmap_special.json
  data/Rebalance_mods/mods/Winning_DDA/Arcana/recipe.json
  data/Rebalance_mods/mods/Winning_DDA/Arcana/recipe_other_WIN.json
  data/Rebalance_mods/mods/Winning_DDA/PK/doomspire.json
  data/Rebalance_mods/mods/Winning_DDA/boss_monsters.json
  data/Rebalance_mods/mods/Winning_DDA/item_groups.json
  data/Rebalance_mods/mods/Winning_DDA/terrain.json
  data/Rebalance_mods/mods/Zets_CDDA_Mod/adv_gear_equipment.json
  data/Rebalance_mods/mods/Zets_CDDA_Mod/adv_gear_mutations.json
  data/Rebalance_mods/mods/Zets_CDDA_Mod/blazemod_blaze_test.json
  data/Rebalance_mods/mods/Zets_CDDA_Mod/cata++_c_armor.json
  data/Rebalance_mods/mods/Zets_CDDA_Mod/dda_armor.json
  data/Rebalance_mods/mods/Zets_CDDA_Mod/dda_tool_armor.json
  data/Rebalance_mods/mods/more_classes_scenarios/cs_professions.json
  data/Rebalance_mods/mods/more_classes_scenarios/modinfo.json
Labels: Experimental F, bug

#290 [Experimental] legacy mod bug fixes
  data/Legacy_mods/mods/HeavyMining/vehicles.json
  data/Legacy_mods/mods/Salvaged_Robots/robot_additions/vehicles.json
  data/Legacy_mods/mods/Tanks/vehicles.json
  data/Legacy_mods/mods/blazemod/vehicleparts/blaze_weapons_parts.json
Labels: Experimental F, bug

#289 [Experimental] maintained mods update
  data/Maintained_mods/mods/Arcana/items/tool_armor.json
  data/Maintained_mods/mods/BL9_100%_monster_resilience_version/Monsters/mon_group.json
  data/Maintained_mods/mods/BL9_140%_monster_resilience_version/Monsters/mon_group.json
  data/Maintained_mods/mods/BL9_175%_monster_resilience_version/Monsters/mon_group.json
  data/Maintained_mods/mods/MST_Extra/monstergroup_additions.json
  data/Maintained_mods/mods/Nocts_cata_mod/Monsters/c_monstergroups.json
  data/Maintained_mods/mods/Nocts_cata_mod/modinfo.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/vehicles/modified.json
  data/Maintained_mods/mods/expansion_tefnut/vehicles/modified.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/items/fuel_override.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/items/gun.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/items/melee.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/items/mutagen.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/monsters/insect.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/pk_professions.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_itemlist_edit.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_monstergroup_doom-science.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_monstergroup_forest-river.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_monstergroup_other.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_monstergroup_triffgus.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_monstergroup_wildy.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_monstergroup_zed.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_spawnlist_doom-science.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_spawnlist_forest-river.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_spawnlist_other.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_spawnlist_triffgus.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_spawnlist_wildy.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_spawnlist_zed.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/vehicle/pk_vehicle_bfg.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/vehicle/pk_vehicle_doubleplow.json
Labels: Experimental F, bug

#288 [Experimental] unleash the mods updates
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_vehicles.json
  data/Unleash_The_Mods/mods/Shard_stuff/override_vehicleparts.json
  data/unleash_The_Mods/mods/Advanced_Gear/definitions.json
  data/unleash_The_Mods/mods/Advanced_Gear/items/gear/multitool.json
  data/unleash_The_Mods/mods/Advanced_Gear/items/vehicle/vehicle_parts.json
  data/unleash_The_Mods/mods/Advanced_Gear/requirement_overrides.json
  data/unleash_The_Mods/mods/Custom_Bandit_King_Start/vehicles.json
  data/unleash_The_Mods/mods/Draco_Dog_Mod/vehicles/dg_vehicles.json
  data/unleash_The_Mods/mods/Fallout/vehicle_gunrunner/gunrunners.json
  data/unleash_The_Mods/mods/Jury_Rigged_Robots/jrr_items.json
  data/unleash_The_Mods/mods/Make_a_Lot_of_Items_Mod/MLI_monstergroup.json
  data/unleash_The_Mods/mods/Mo_Vehicles/veh.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Domestic.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Forest.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/House.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/IchBinNexus.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Labs_and_Robots.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Mansion.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Pharm.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Publicworkers.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Safe.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Sludge_Sewer_Cave.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Swamp.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Vanilla.json
  data/unleash_The_Mods/mods/Monstergroups_Combo_Patch/Zombies_and_Fungus.json
  data/unleash_The_Mods/mods/Ninja_mod/ninja_vehicle.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/items/lighting_override.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/mod_tileset/mod_tileset.json
  data/unleash_The_Mods/mods/Warhammer_40K/monstergroups.json
  data/unleash_The_Mods/mods/miso_Touhou/item_touhou/item_touhou.json
  data/unleash_The_Mods/mods/stomach_offal/food.json
Labels: Experimental F, bug

#287 [Experimental] mainline mods update
  data/Mainline_mods/Mods/Aftershock/vehicles/vehicle_overrides.json
  data/Mainline_mods/Mods/Aftershock/vehicles/vehicles.json
  data/Mainline_mods/Mods/BlazeIndustries/vehicleparts/blaze_turrets_vanilla.json
  data/Mainline_mods/Mods/Magiclysm/Spells/attunements/Glacier_Mage.json
  data/Mainline_mods/Mods/Magiclysm/Spells/magus.json
  data/Mainline_mods/Mods/Magiclysm/Spells/stormshaper.json
  data/Mainline_mods/Mods/Magiclysm/Spells/technomancer.json
  data/Mainline_mods/Mods/Magiclysm/effects/effects.json
  data/Mainline_mods/Mods/Magiclysm/field.json
  data/Mainline_mods/Mods/Magiclysm/harvest.json
  data/Mainline_mods/Mods/Magiclysm/itemgroups/itemgroups.json
  data/Mainline_mods/Mods/Magiclysm/itemgroups/spellbooks.json
  data/Mainline_mods/Mods/Magiclysm/items/spell_scrolls.json
  data/Mainline_mods/Mods/Magiclysm/items/spellbooks.json
  data/Mainline_mods/Mods/Magiclysm/monster_factions.json
  data/Mainline_mods/Mods/Magiclysm/monstergroups.json
  data/Mainline_mods/Mods/Magiclysm/monsters/golems.json
  data/Mainline_mods/Mods/Magiclysm/npc/npc.json
  data/Mainline_mods/Mods/Magiclysm/professions.json
  data/Mainline_mods/Mods/Magiclysm/requirements/spell_components.json
  data/Mainline_mods/Mods/Magiclysm/species.json
  data/Mainline_mods/Mods/Magiclysm/terrain.json
  data/Mainline_mods/Mods/Magiclysm/traits/attunements.json
  data/Mainline_mods/Mods/Magiclysm/vehicles/summoned_vehicles.json
  data/Mainline_mods/Mods/Magiclysm/worldgen/magic_shop.json
  data/Maintained_mods/mods/Arcana/npcs/npcs.json
Labels: Experimental F, bug

#291 [Experimental] broken mods bug fixes
  data/Mainline_mods/Mods/Magiclysm/vehicles/summoned_vehicles.json
  data/broken_mods/Car_color_variation/vehicles.json
  data/broken_mods/OP_Pack/tools.json
  data/broken_mods/Standalone_Salvaged_Robots/corpses.json
  data/broken_mods/Standalone_Salvaged_Robots/corpses_SR.json
  data/broken_mods/Standalone_Salvaged_Robots/items.json
  data/broken_mods/Standalone_Salvaged_Robots/recipe.json
  data/broken_mods/Standalone_Salvaged_Robots/robot_additions/vehicles.json
  data/broken_mods/Standalone_Salvaged_Robots/uncraft_corpse.json
  data/broken_mods/Standalone_Salvaged_Robots/uncraft_corpse_SR.json
Labels: Experimental F, bug
