Repository TheGoatGod/Community-Mod-Compilation, pull requests merged in 2021-01, with the labels that each got.

#212 [Experimental] Alternate ear graphics
  data/unleash_The_Mods/mods/Alternate_ear_graphics/cosmetic_armor.json
  data/unleash_The_Mods/mods/Alternate_ear_graphics/mod_tileset/mod_tileset.json
  data/unleash_The_Mods/mods/Alternate_ear_graphics/modinfo.json
Labels: Experimental F, bug

#213 [Experimental] Bayonet mod
  data/Unleash_The_Mods/mods/Bayonet_mod/documents/README.md
  data/Unleash_The_Mods/mods/Bayonet_mod/documents/optional guns.txt
  data/Unleash_The_Mods/mods/Bayonet_mod/items/bayoitems.json
  data/Unleash_The_Mods/mods/Bayonet_mod/items/martial_arts_manuals.json
  data/Unleash_The_Mods/mods/Bayonet_mod/martialarts_and_techniques/martialarts.json
  data/Unleash_The_Mods/mods/Bayonet_mod/martialarts_and_techniques/techniques.json
  data/unleash_The_Mods/mods/Bayonet_mod/optional guns.txt
Labels: Experimental F, documentation, enhancement

#214 [Experimental] Basement extension
  data/Unleash_The_Mods/Working_mods/Basement_Extension/basement_pets.json
  data/Unleash_The_Mods/Working_mods/Basement_Extension/itemgroups/basic_item_groups.json
  data/Unleash_The_Mods/Working_mods/Basement_Extension/itemgroups/chem_item_groups.json
  data/Unleash_The_Mods/Working_mods/Basement_Extension/itemgroups/pets_item_groups.json
  data/Unleash_The_Mods/Working_mods/Basement_Extension/itemgroups/pets_monstor_groups.json
  data/Unleash_The_Mods/Working_mods/Basement_Extension/mapgen/basement_basic_01.json
  data/Unleash_The_Mods/Working_mods/Basement_Extension/mapgen/basement_chem.json
  data/Unleash_The_Mods/Working_mods/Basement_Extension/mapgen/basement_pets.json
Labels: Experimental F, documentation, enhancement

#217 [Experimental] json - Mod tileset fix
  data/Legacy_mods/mods/blazemod/mod_tileset/mod_tileset.json
  data/Mainline_mods/Mods/Aftershock/mod_tileset/mod_tileset.json
  data/Mainline_mods/Mods/BlazeIndustries/mod_tileset/mod_tileset.json
  data/Mainline_mods/Mods/Generic_Guns/mod_tileset/mod_tileset.json
  data/Mainline_mods/Mods/Magiclysm/mod_tileset/mod_tileset.json
  data/Maintained_mods/mods/Mining_Mod/mod_tileset/mod_tileset.json
  data/broken_mods/Car_color_variation/mod_tileset/mod_tileset.json
  data/unleash_The_Mods/mods/Advanced_Gear/mod_tileset/mod_tileset.json
  data/unleash_The_Mods/mods/Nocts_cata_mod/mod_tileset/mod_tileset.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/mod_tileset/mod_tileset.json
  data/unleash_The_Mods/mods/Tankmod_Revived/mod_tileset/mod_tileset.json
  json_blacklist
Labels: Experimental F, documentation, enhancement, invalid, tileset

#218 [Experimental] Add new mod TropiCataclysm
  data/Unleash_The_Mods/mods/TropiCataclysm/blacklists/mon_blacklist.json
  data/Unleash_The_Mods/mods/TropiCataclysm/items/egg.json
  data/Unleash_The_Mods/mods/TropiCataclysm/modinfo.json
  data/Unleash_The_Mods/mods/TropiCataclysm/monstergroups/eggs.json
  data/Unleash_The_Mods/mods/TropiCataclysm/monstergroups/wilderness.json
  data/Unleash_The_Mods/mods/TropiCataclysm/monsters/tropical_bird.json
  data/Unleash_The_Mods/mods/TropiCataclysm/monsters/tropical_insect_spider.json
  data/Unleash_The_Mods/mods/TropiCataclysm/monsters/tropical_mammal.json
  data/Unleash_The_Mods/mods/TropiCataclysm/monsters/tropical_monsters.json
  data/Unleash_The_Mods/mods/TropiCataclysm/monsters/tropical_reptile_amphibian.json
  data/Unleash_The_Mods/mods/TropiCataclysm/monsters/tropical_zanimal.json
  data/Unleash_The_Mods/mods/TropiCataclysm/tropical_monster_factions.json
  data/Unleash_The_Mods/mods/TropiCataclysm/tropical_overmap_connections.json
  data/Unleash_The_Mods/mods/TropiCataclysm/tropical_overmap_terrain.json
  data/Unleash_The_Mods/mods/TropiCataclysm/tropical_regional_map_settings.json
  data/Unleash_The_Mods/mods/TropiCataclysm/tropical_special_locations.json
  data/Unleash_The_Mods/mods/TropiCataclysm/tropical_terrain.json
Labels: Experimental F, New Mod

#220 [Documentation] Override a variable.md
  Documents/Override a variable.md
Labels: documentation

#221 [Experimental] Jury Rigged Robots fixes and tweaks
  data/Unleash_The_Mods/mods/Jury_Rigged_Robots/jrr_new_bots.json
  data/unleash_The_Mods/mods/Jury_Rigged_Robots/jrr_monster_override.json
  data/unleash_The_Mods/mods/Jury_Rigged_Robots/jrr_rigged_bots.json
Labels: Experimental F, enhancement

#224 [Experimental] Misc Magiclysm Expansions content update
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/effects.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mapgen/overmap_specials.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mapgen/overmap_terrain.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mapgen/snippets.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mapgen/terrain.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mapgen/wizard/wizard_shack.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mutagenics/dreams.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/recipiebooks.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/recipies/gstaves.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/recipies/magazines.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/recipies/staves.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/spells/classless.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/spells/frostmonger.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/spells/innate.json
  data/Unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/spells/pyromancer.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/enchanted/enchanted_staves.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mapgen/itemgroups.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/monsters/atro.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/monsters/undead.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mutagenics/categories.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mutagenics/classes.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mutagenics/mutagen.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mutagenics/mutations/magic.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/mutagenics/recipiebooks.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/recepies.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/recipies/alchemy/potions.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/scenarios.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/ecreatures.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/eitems.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/spellbooks.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/spells.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/spells/atromancer.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/spells/necro.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/spells/spells/summoner.json
  data/unleash_The_Mods/mods/Miscellaneous_Magiclysm_Expansions/start_location.json
Labels: Experimental F, added content, lint update

#226 [Experimental] add new mods
  data/Unleash_The_Mods/Working_mods/Arendeths_Mutant_Cyborg_Profession/modinfo.json
  data/Unleash_The_Mods/Working_mods/Arendeths_Mutant_Cyborg_Profession/professions.json
  data/Unleash_The_Mods/Working_mods/Arendeths_Mutant_Cyborg_Profession/scenarios.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/exclusions.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/harvest.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/items.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/laser_items.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/modinfo.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monsterdrops/dinodrops.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monsterdrops/zombiehumandrops.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monstergroups/dino_science_groups.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monsters/cbm_dinos.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monsters/cbm_zinos.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monsters/civillian_dinos.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monsters/civillian_zinos.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monsters/laser_dinos_zinos.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monsters/prison_dinos_zinos.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monsters/worker_dinos.json
  data/Unleash_The_Mods/Working_mods/Dino_Mad_Science/monsters/zombie_humans.json
Labels: New Mod

#237 [Documentation] fixes documents
  Documents/Gun_Mods_install_times.md
  Documents/Installation_guide.md
  Documents/Learning_Code.md
  Documents/Updating_Legacy_JSON.md
Labels: documentation

#244 [Experimental] update expansion tefnut
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/armor/armor_fake.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/armor/boots.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/armor/lewd.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/armor/maid.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/armor/misc.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/armor/misc_survivor.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/armor/wrist.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/gun_762x54.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/gun_950.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/gun_boys.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/gun_gyrojet.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/gun_shot.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/japanese/clothing.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/japanese/gun_rifle.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/revolvers/revolvers_rifle.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/ww2_america/american_uniforms.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/ww2_america/gun_pistol.json
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/ww2_america/gun_rifle.json
  data/Maintained_mods/mods/expansion_tefnut/items/armor/armor_fake.json
  data/Maintained_mods/mods/expansion_tefnut/items/armor/boots.json
  data/Maintained_mods/mods/expansion_tefnut/items/armor/lewd.json
  data/Maintained_mods/mods/expansion_tefnut/items/armor/maid.json
  data/Maintained_mods/mods/expansion_tefnut/items/armor/misc.json
  data/Maintained_mods/mods/expansion_tefnut/items/armor/misc_survivor.json
  data/Maintained_mods/mods/expansion_tefnut/items/armor/wrist.json
  data/Maintained_mods/mods/expansion_tefnut/items/guns/gun_950.json
  data/Maintained_mods/mods/expansion_tefnut/items/guns/gun_boys.json
  data/Maintained_mods/mods/expansion_tefnut/items/guns/gun_gyrojet.json
  data/Maintained_mods/mods/expansion_tefnut/items/guns/japanese/clothing.json
  data/Maintained_mods/mods/expansion_tefnut/items/guns/japanese/gun_rifle.json
  data/Maintained_mods/mods/expansion_tefnut/items/guns/revolvers/revolvers_rifle.json
  data/Maintained_mods/mods/expansion_tefnut/items/guns/ww2_america/american_uniforms.json
  data/Maintained_mods/mods/expansion_tefnut/items/guns/ww2_america/gun_pistol.json
  data/Maintained_mods/mods/expansion_tefnut/items/guns/ww2_america/gun_rifle.json
Labels: Experimental F, enhancement

#248 [Experimental] mod Tileset updates
  data/Maintained_mods/mods/Dark_Skies_Above_Kenans_Version/mod_tileset/Dark_Skies_Above_large.png
  data/Maintained_mods/mods/Dark_Skies_Above_Kenans_Version/mod_tileset/Dark_Skies_Above_normal.png
  data/Maintained_mods/mods/Dark_Skies_Above_Kenans_Version/mod_tileset/mod_tileset.json
  data/unleash_The_Mods/mods/Artyom_Emporium/mod_tileset/mod_tileset.json
  data/unleash_The_Mods/mods/Tankmod_Revived/mod_tileset/mod_tileset.json
Labels: Experimental F, tileset

#245 [Experimental] Update tefnut
  data/Maintained_mods/mods/expansion_tefnut/expansion_tefnut/items/guns/ww2_america/gun_pistol.json
  data/Maintained_mods/mods/expansion_tefnut/items/guns/ww2_america/gun_pistol.json
Labels: Experimental F, enhancement

#251 [Experimental] update all round BL9
  data/Maintained_mods/mods/BL9_100%_monster_resilience_version/Items/martial_extension.json
  data/Maintained_mods/mods/BL9_100%_monster_resilience_version/Items/weapons.json
  data/Maintained_mods/mods/BL9_100%_monster_resilience_version/Locations/Anomalies.json
  data/Maintained_mods/mods/BL9_100%_monster_resilience_version/Locations/Castlelan_entrance.json
  data/Maintained_mods/mods/BL9_100%_monster_resilience_version/Locations/Castlelan_update.json
  data/Maintained_mods/mods/BL9_100%_monster_resilience_version/Monsters/mon_spell.json
  data/Maintained_mods/mods/BL9_100%_monster_resilience_version/modinfo.json
  data/Maintained_mods/mods/BL9_140%_monster_resilience_version/Items/martial_extension.json
  data/Maintained_mods/mods/BL9_140%_monster_resilience_version/Items/weapons.json
  data/Maintained_mods/mods/BL9_140%_monster_resilience_version/Locations/Anomalies.json
  data/Maintained_mods/mods/BL9_140%_monster_resilience_version/Locations/Castlelan_entrance.json
  data/Maintained_mods/mods/BL9_140%_monster_resilience_version/Locations/Castlelan_update.json
  data/Maintained_mods/mods/BL9_140%_monster_resilience_version/Monsters/mon_spell.json
  data/Maintained_mods/mods/BL9_140%_monster_resilience_version/modinfo.json
  data/Maintained_mods/mods/BL9_175%_monster_resilience_version/Items/martial_extension.json
  data/Maintained_mods/mods/BL9_175%_monster_resilience_version/Items/weapons.json
  data/Maintained_mods/mods/BL9_175%_monster_resilience_version/Locations/Anomalies.json
  data/Maintained_mods/mods/BL9_175%_monster_resilience_version/Locations/Castlelan_entrance.json
  data/Maintained_mods/mods/BL9_175%_monster_resilience_version/Locations/Castlelan_update.json
  data/Maintained_mods/mods/BL9_175%_monster_resilience_version/Monsters/mon_spell.json
  data/Maintained_mods/mods/BL9_175%_monster_resilience_version/modinfo.json
Labels: Experimental F

#252 [Experimental] pk rebalacing
  data/unleash_The_Mods/mods/PKs_Rebalancing/items/ammo.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/items/armor.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/items/gun.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/items/vehicle_parts.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/mod_tileset/mod_tileset.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/pk_emit.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/pk_recipe.json
  data/unleash_The_Mods/mods/PKs_Rebalancing/spawns/pk_monstergroup_wildy.json
Labels: Experimental F

#228 [Experimental] Move working mod
  data/Rebalance_mods/mods/ShardsOtherStuff_UNINSTALLED/disable_bots/disable.json
  data/Rebalance_mods/mods/ShardsOtherStuff_UNINSTALLED/disable_bots_natcamp/disable.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_clothing_mods.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_flags.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_guns.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_itemgroups.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_items.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_mutations.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_recipes.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_scenarios.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_start_locations.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_vehicle_parts.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/42sm_vehicles.json
  data/Unleash_The_Mods/Working_mods/42_small_mod/modinfo.json
  data/Unleash_The_Mods/mods/PKs_Rebalancing/PKs_discontinued_code.txt
  data/broken_mods/Alchemic_bomb/alc_item.json
  data/broken_mods/Standalone_Salvaged_Robots/items.json
  data/broken_mods/Standalone_Salvaged_Robots/items_SR.json
  data/unleash_The_Mods/mods/Anti_fungus_kit/items.json
  data/unleash_The_Mods/mods/Civilian_Salvaged_Robots/civilian_robots/items.json
  data/unleash_The_Mods/mods/Civilian_Salvaged_Robots/modified_robots/items.json
  data/unleash_The_Mods/mods/Fallout/Gunsmiths_Guru/items/inactive_bots.json
  data/unleash_The_Mods/mods/Modular_Turrets_Remake/items.json
  data/unleash_The_Mods/mods/No_Hope_Night_Pryanik/Items/tools.json
  data/unleash_The_Mods/mods/Science_Additions/turret_item.json
  data/unleash_The_Mods/mods/Vorpal_Weapons/vo_tools.json
  data/unleash_The_Mods/mods/battletech/Infantry/Weaponry/Missiles/SRM/SRM.json
  data/unleash_The_Mods/mods/miso_Touhou/hentai_touhou/Hentai.json
  data/unleash_The_Mods/mods/miso_Touhou/item_touhou/alice_bot.json
  data/unleash_The_Mods/mods/miso_Touhou/item_touhou/item_touhou.json
  data/unleash_The_Mods/mods/miso_Touyou/item/item.json
Labels: Experimental F
